steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/strategic-reef-435523-j1/myapp:latest', '-f', 'Backend/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/strategic-reef-435523-j1/myapp:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/myapp-deployment'
    - 'myapp=gcr.io/strategic-reef-435523-j1/myapp:latest'
    - '--namespace=myapp'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images:
  - 'gcr.io/strategic-reef-435523-j1/myapp:latest'
substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'cluster-1'
options:
  logging: GCS_ONLY
logsBucket: gs://todo-app-build-logs-strategic-reef-435523
