steps:
# Backend Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'strategic-reef-435523-j1/myapp:latest', '-f', 'backend/Dockerfile', '.']  # Adjust if Dockerfile is in a subdirectory
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/strategic-reef-435523-j1/myapp:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/myapp-deployment'
    - 'myapp=gcr.io/strategic-reef-435523-j1/myapp:latest'
    - '--namespace=myapp'

# Frontend Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'strategic-reef-435523-j1/frontend:latest', '-f', 'frontend/Dockerfile', 'frontend/']  # Path to frontend Dockerfile and build context
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/strategic-reef-435523-j1/frontend:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/frontend-deployment'
    - 'frontend=gcr.io/strategic-reef-435523-j1/frontend:latest'
    - '--namespace=frontend'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/strategic-reef-435523-j1/myapp:latest'
  - 'gcr.io/strategic-reef-435523-j1/frontend:latest'

substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'cluster-1'

options:
  logging: GCS_ONLY

logsBucket: gs://todo-app-build-logs-strategic-reef-435523
